/*
 * Fuse
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fuse.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.fuse.client.model.CreateLinkTokenRequestTellerConfigAccountFilter;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.fuse.client.JSON;

/**
 * CreateLinkTokenRequestTellerConfig
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-02-23T12:03:45.546785Z[UTC]")
public class CreateLinkTokenRequestTellerConfig {
  /**
   * The mode of account selection: - &#39;disabled&#39;: automatically connect all the supported financial accounts associated with this user&#39;s account at the institution (default). - &#39;single&#39;: the user will see a list of supported financial accounts and will need to select one to connect - &#39;multiple&#39;: the user will see a list of supported financial accounts and will need to select one or more to connect
   */
  @JsonAdapter(SelectAccountEnum.Adapter.class)
  public enum SelectAccountEnum {
    DISABLED("disabled"),
    
    SINGLE("single"),
    
    MULTIPLE("multiple");

    private String value;

    SelectAccountEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static SelectAccountEnum fromValue(String value) {
      for (SelectAccountEnum b : SelectAccountEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<SelectAccountEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final SelectAccountEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public SelectAccountEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return SelectAccountEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      SelectAccountEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_SELECT_ACCOUNT = "selectAccount";
  @SerializedName(SERIALIZED_NAME_SELECT_ACCOUNT)
  private SelectAccountEnum selectAccount;

  public static final String SERIALIZED_NAME_ACCOUNT_FILTER = "accountFilter";
  @SerializedName(SERIALIZED_NAME_ACCOUNT_FILTER)
  private CreateLinkTokenRequestTellerConfigAccountFilter accountFilter;

  public CreateLinkTokenRequestTellerConfig() {
  }

  public CreateLinkTokenRequestTellerConfig selectAccount(SelectAccountEnum selectAccount) {
    this.selectAccount = selectAccount;
    return this;
  }

   /**
   * The mode of account selection: - &#39;disabled&#39;: automatically connect all the supported financial accounts associated with this user&#39;s account at the institution (default). - &#39;single&#39;: the user will see a list of supported financial accounts and will need to select one to connect - &#39;multiple&#39;: the user will see a list of supported financial accounts and will need to select one or more to connect
   * @return selectAccount
  **/
  @javax.annotation.Nullable
  public SelectAccountEnum getSelectAccount() {
    return selectAccount;
  }

  public void setSelectAccount(SelectAccountEnum selectAccount) {
    this.selectAccount = selectAccount;
  }


  public CreateLinkTokenRequestTellerConfig accountFilter(CreateLinkTokenRequestTellerConfigAccountFilter accountFilter) {
    this.accountFilter = accountFilter;
    return this;
  }

   /**
   * Get accountFilter
   * @return accountFilter
  **/
  @javax.annotation.Nullable
  public CreateLinkTokenRequestTellerConfigAccountFilter getAccountFilter() {
    return accountFilter;
  }

  public void setAccountFilter(CreateLinkTokenRequestTellerConfigAccountFilter accountFilter) {
    this.accountFilter = accountFilter;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateLinkTokenRequestTellerConfig createLinkTokenRequestTellerConfig = (CreateLinkTokenRequestTellerConfig) o;
    return Objects.equals(this.selectAccount, createLinkTokenRequestTellerConfig.selectAccount) &&
        Objects.equals(this.accountFilter, createLinkTokenRequestTellerConfig.accountFilter);
  }

  @Override
  public int hashCode() {
    return Objects.hash(selectAccount, accountFilter);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateLinkTokenRequestTellerConfig {\n");
    sb.append("    selectAccount: ").append(toIndentedString(selectAccount)).append("\n");
    sb.append("    accountFilter: ").append(toIndentedString(accountFilter)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("selectAccount");
    openapiFields.add("accountFilter");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to CreateLinkTokenRequestTellerConfig
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CreateLinkTokenRequestTellerConfig.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CreateLinkTokenRequestTellerConfig is not found in the empty JSON string", CreateLinkTokenRequestTellerConfig.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CreateLinkTokenRequestTellerConfig.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `CreateLinkTokenRequestTellerConfig` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("selectAccount") != null && !jsonObj.get("selectAccount").isJsonNull()) && !jsonObj.get("selectAccount").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `selectAccount` to be a primitive type in the JSON string but got `%s`", jsonObj.get("selectAccount").toString()));
      }
      // validate the optional field `selectAccount`
      if (jsonObj.get("selectAccount") != null && !jsonObj.get("selectAccount").isJsonNull()) {
        SelectAccountEnum.validateJsonElement(jsonObj.get("selectAccount"));
      }
      // validate the optional field `accountFilter`
      if (jsonObj.get("accountFilter") != null && !jsonObj.get("accountFilter").isJsonNull()) {
        CreateLinkTokenRequestTellerConfigAccountFilter.validateJsonElement(jsonObj.get("accountFilter"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CreateLinkTokenRequestTellerConfig.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CreateLinkTokenRequestTellerConfig' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CreateLinkTokenRequestTellerConfig> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CreateLinkTokenRequestTellerConfig.class));

       return (TypeAdapter<T>) new TypeAdapter<CreateLinkTokenRequestTellerConfig>() {
           @Override
           public void write(JsonWriter out, CreateLinkTokenRequestTellerConfig value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CreateLinkTokenRequestTellerConfig read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of CreateLinkTokenRequestTellerConfig given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of CreateLinkTokenRequestTellerConfig
  * @throws IOException if the JSON string is invalid with respect to CreateLinkTokenRequestTellerConfig
  */
  public static CreateLinkTokenRequestTellerConfig fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CreateLinkTokenRequestTellerConfig.class);
  }

 /**
  * Convert an instance of CreateLinkTokenRequestTellerConfig to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

