/*
 * Fuse
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fuse.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.fuse.client.model.ConsumerRiskReport;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.fuse.client.JSON;

/**
 * GetConsumerRiskReportResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-09-12T14:48:18.188409Z[UTC]")
public class GetConsumerRiskReportResponse {
  public static final String SERIALIZED_NAME_CONSUMER_RISK_REPORT = "consumer_risk_report";
  @SerializedName(SERIALIZED_NAME_CONSUMER_RISK_REPORT)
  private ConsumerRiskReport consumerRiskReport;

  public static final String SERIALIZED_NAME_REQUEST_ID = "request_id";
  @SerializedName(SERIALIZED_NAME_REQUEST_ID)
  private String requestId;

  public GetConsumerRiskReportResponse() {
  }

  public GetConsumerRiskReportResponse consumerRiskReport(ConsumerRiskReport consumerRiskReport) {
    
    this.consumerRiskReport = consumerRiskReport;
    return this;
  }

   /**
   * Get consumerRiskReport
   * @return consumerRiskReport
  **/
  @javax.annotation.Nonnull
  public ConsumerRiskReport getConsumerRiskReport() {
    return consumerRiskReport;
  }


  public void setConsumerRiskReport(ConsumerRiskReport consumerRiskReport) {
    this.consumerRiskReport = consumerRiskReport;
  }


  public GetConsumerRiskReportResponse requestId(String requestId) {
    
    this.requestId = requestId;
    return this;
  }

   /**
   * An identifier that is exclusive to the request and can serve as a means for investigating and resolving issues.
   * @return requestId
  **/
  @javax.annotation.Nonnull
  public String getRequestId() {
    return requestId;
  }


  public void setRequestId(String requestId) {
    this.requestId = requestId;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetConsumerRiskReportResponse getConsumerRiskReportResponse = (GetConsumerRiskReportResponse) o;
    return Objects.equals(this.consumerRiskReport, getConsumerRiskReportResponse.consumerRiskReport) &&
        Objects.equals(this.requestId, getConsumerRiskReportResponse.requestId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(consumerRiskReport, requestId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetConsumerRiskReportResponse {\n");
    sb.append("    consumerRiskReport: ").append(toIndentedString(consumerRiskReport)).append("\n");
    sb.append("    requestId: ").append(toIndentedString(requestId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("consumer_risk_report");
    openapiFields.add("request_id");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("consumer_risk_report");
    openapiRequiredFields.add("request_id");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to GetConsumerRiskReportResponse
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GetConsumerRiskReportResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in GetConsumerRiskReportResponse is not found in the empty JSON string", GetConsumerRiskReportResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!GetConsumerRiskReportResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `GetConsumerRiskReportResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : GetConsumerRiskReportResponse.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `consumer_risk_report`
      ConsumerRiskReport.validateJsonElement(jsonObj.get("consumer_risk_report"));
      if (!jsonObj.get("request_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `request_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("request_id").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GetConsumerRiskReportResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GetConsumerRiskReportResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GetConsumerRiskReportResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GetConsumerRiskReportResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<GetConsumerRiskReportResponse>() {
           @Override
           public void write(JsonWriter out, GetConsumerRiskReportResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GetConsumerRiskReportResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of GetConsumerRiskReportResponse given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of GetConsumerRiskReportResponse
  * @throws IOException if the JSON string is invalid with respect to GetConsumerRiskReportResponse
  */
  public static GetConsumerRiskReportResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GetConsumerRiskReportResponse.class);
  }

 /**
  * Convert an instance of GetConsumerRiskReportResponse to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

