/*
 * Fuse
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fuse.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.fuse.client.JSON;

/**
 * SelectFinancialInstitutionsRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-02-23T12:03:45.546785Z[UTC]")
public class SelectFinancialInstitutionsRequest {
  public static final String SERIALIZED_NAME_SESSION_CLIENT_SECRET = "session_client_secret";
  @SerializedName(SERIALIZED_NAME_SESSION_CLIENT_SECRET)
  private String sessionClientSecret;

  public static final String SERIALIZED_NAME_FINANCIAL_INSTITUTION_ID = "financial_institution_id";
  @SerializedName(SERIALIZED_NAME_FINANCIAL_INSTITUTION_ID)
  private String financialInstitutionId;

  public SelectFinancialInstitutionsRequest() {
  }

  public SelectFinancialInstitutionsRequest sessionClientSecret(String sessionClientSecret) {
    this.sessionClientSecret = sessionClientSecret;
    return this;
  }

   /**
   * The session client secret created.
   * @return sessionClientSecret
  **/
  @javax.annotation.Nonnull
  public String getSessionClientSecret() {
    return sessionClientSecret;
  }

  public void setSessionClientSecret(String sessionClientSecret) {
    this.sessionClientSecret = sessionClientSecret;
  }


  public SelectFinancialInstitutionsRequest financialInstitutionId(String financialInstitutionId) {
    this.financialInstitutionId = financialInstitutionId;
    return this;
  }

   /**
   * The selected financial institution id
   * @return financialInstitutionId
  **/
  @javax.annotation.Nonnull
  public String getFinancialInstitutionId() {
    return financialInstitutionId;
  }

  public void setFinancialInstitutionId(String financialInstitutionId) {
    this.financialInstitutionId = financialInstitutionId;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SelectFinancialInstitutionsRequest selectFinancialInstitutionsRequest = (SelectFinancialInstitutionsRequest) o;
    return Objects.equals(this.sessionClientSecret, selectFinancialInstitutionsRequest.sessionClientSecret) &&
        Objects.equals(this.financialInstitutionId, selectFinancialInstitutionsRequest.financialInstitutionId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sessionClientSecret, financialInstitutionId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SelectFinancialInstitutionsRequest {\n");
    sb.append("    sessionClientSecret: ").append(toIndentedString(sessionClientSecret)).append("\n");
    sb.append("    financialInstitutionId: ").append(toIndentedString(financialInstitutionId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("session_client_secret");
    openapiFields.add("financial_institution_id");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("session_client_secret");
    openapiRequiredFields.add("financial_institution_id");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to SelectFinancialInstitutionsRequest
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!SelectFinancialInstitutionsRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in SelectFinancialInstitutionsRequest is not found in the empty JSON string", SelectFinancialInstitutionsRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!SelectFinancialInstitutionsRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `SelectFinancialInstitutionsRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : SelectFinancialInstitutionsRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("session_client_secret").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `session_client_secret` to be a primitive type in the JSON string but got `%s`", jsonObj.get("session_client_secret").toString()));
      }
      if (!jsonObj.get("financial_institution_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `financial_institution_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("financial_institution_id").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SelectFinancialInstitutionsRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SelectFinancialInstitutionsRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SelectFinancialInstitutionsRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SelectFinancialInstitutionsRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<SelectFinancialInstitutionsRequest>() {
           @Override
           public void write(JsonWriter out, SelectFinancialInstitutionsRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public SelectFinancialInstitutionsRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of SelectFinancialInstitutionsRequest given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of SelectFinancialInstitutionsRequest
  * @throws IOException if the JSON string is invalid with respect to SelectFinancialInstitutionsRequest
  */
  public static SelectFinancialInstitutionsRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SelectFinancialInstitutionsRequest.class);
  }

 /**
  * Convert an instance of SelectFinancialInstitutionsRequest to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

