/*
 * Fuse
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.AssetReportAccountsInner;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AssetReport
 */
public class AssetReportTest {
    private final AssetReport model = new AssetReport();

    /**
     * Model tests for AssetReport
     */
    @Test
    public void testAssetReport() {
        // TODO: test AssetReport
    }

    /**
     * Test the property 'assetReportId'
     */
    @Test
    public void assetReportIdTest() {
        // TODO: test assetReportId
    }

    /**
     * Test the property 'assetReportToken'
     */
    @Test
    public void assetReportTokenTest() {
        // TODO: test assetReportToken
    }

    /**
     * Test the property 'dateGenerated'
     */
    @Test
    public void dateGeneratedTest() {
        // TODO: test dateGenerated
    }

    /**
     * Test the property 'daysRequested'
     */
    @Test
    public void daysRequestedTest() {
        // TODO: test daysRequested
    }

    /**
     * Test the property 'accounts'
     */
    @Test
    public void accountsTest() {
        // TODO: test accounts
    }

}
