/*
 * Fuse
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AssetReportAccountsInnerHistoricalBalancesInner
 */
public class AssetReportAccountsInnerHistoricalBalancesInnerTest {
    private final AssetReportAccountsInnerHistoricalBalancesInner model = new AssetReportAccountsInnerHistoricalBalancesInner();

    /**
     * Model tests for AssetReportAccountsInnerHistoricalBalancesInner
     */
    @Test
    public void testAssetReportAccountsInnerHistoricalBalancesInner() {
        // TODO: test AssetReportAccountsInnerHistoricalBalancesInner
    }

    /**
     * Test the property 'date'
     */
    @Test
    public void dateTest() {
        // TODO: test date
    }

    /**
     * Test the property 'current'
     */
    @Test
    public void currentTest() {
        // TODO: test current
    }

    /**
     * Test the property 'isoCurrencyCode'
     */
    @Test
    public void isoCurrencyCodeTest() {
        // TODO: test isoCurrencyCode
    }

}
