/*
 * Fuse
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for FinancialConnectionsAccountLiabilityAllOfAprs
 */
public class FinancialConnectionsAccountLiabilityAllOfAprsTest {
    private final FinancialConnectionsAccountLiabilityAllOfAprs model = new FinancialConnectionsAccountLiabilityAllOfAprs();

    /**
     * Model tests for FinancialConnectionsAccountLiabilityAllOfAprs
     */
    @Test
    public void testFinancialConnectionsAccountLiabilityAllOfAprs() {
        // TODO: test FinancialConnectionsAccountLiabilityAllOfAprs
    }

    /**
     * Test the property 'aprPercentage'
     */
    @Test
    public void aprPercentageTest() {
        // TODO: test aprPercentage
    }

    /**
     * Test the property 'aprType'
     */
    @Test
    public void aprTypeTest() {
        // TODO: test aprType
    }

}
