/*
 * Fuse
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.FinancialConnectionsOwnerAddressesInner;
import org.openapitools.client.model.FinancialConnectionsOwnerEmailsInner;
import org.openapitools.client.model.FinancialConnectionsOwnerNamesInner;
import org.openapitools.client.model.FinancialConnectionsOwnerPhoneNumbersInner;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for FinancialConnectionsOwner
 */
public class FinancialConnectionsOwnerTest {
    private final FinancialConnectionsOwner model = new FinancialConnectionsOwner();

    /**
     * Model tests for FinancialConnectionsOwner
     */
    @Test
    public void testFinancialConnectionsOwner() {
        // TODO: test FinancialConnectionsOwner
    }

    /**
     * Test the property 'addresses'
     */
    @Test
    public void addressesTest() {
        // TODO: test addresses
    }

    /**
     * Test the property 'emails'
     */
    @Test
    public void emailsTest() {
        // TODO: test emails
    }

    /**
     * Test the property 'names'
     */
    @Test
    public void namesTest() {
        // TODO: test names
    }

    /**
     * Test the property 'phoneNumbers'
     */
    @Test
    public void phoneNumbersTest() {
        // TODO: test phoneNumbers
    }

}
