/*
 * Fuse
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for FinancialConnectionsAccountDetailsAch
 */
public class FinancialConnectionsAccountDetailsAchTest {
    private final FinancialConnectionsAccountDetailsAch model = new FinancialConnectionsAccountDetailsAch();

    /**
     * Model tests for FinancialConnectionsAccountDetailsAch
     */
    @Test
    public void testFinancialConnectionsAccountDetailsAch() {
        // TODO: test FinancialConnectionsAccountDetailsAch
    }

    /**
     * Test the property 'account'
     */
    @Test
    public void accountTest() {
        // TODO: test account
    }

    /**
     * Test the property 'routing'
     */
    @Test
    public void routingTest() {
        // TODO: test routing
    }

    /**
     * Test the property 'wireRouting'
     */
    @Test
    public void wireRoutingTest() {
        // TODO: test wireRouting
    }

    /**
     * Test the property 'bacsRouting'
     */
    @Test
    public void bacsRoutingTest() {
        // TODO: test bacsRouting
    }

}
