/*
 * Fuse
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.Aggregator;
import org.openapitools.client.model.FuseApiAggregatorError;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for FuseApiErrorData
 */
public class FuseApiErrorDataTest {
    private final FuseApiErrorData model = new FuseApiErrorData();

    /**
     * Model tests for FuseApiErrorData
     */
    @Test
    public void testFuseApiErrorData() {
        // TODO: test FuseApiErrorData
    }

    /**
     * Test the property 'aggregator'
     */
    @Test
    public void aggregatorTest() {
        // TODO: test aggregator
    }

    /**
     * Test the property 'errors'
     */
    @Test
    public void errorsTest() {
        // TODO: test errors
    }

}
