/*
 * Fuse
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.FinancialConnectionsOwner;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetFinancialConnectionsOwnersResponseAccountsInner
 */
public class GetFinancialConnectionsOwnersResponseAccountsInnerTest {
    private final GetFinancialConnectionsOwnersResponseAccountsInner model = new GetFinancialConnectionsOwnersResponseAccountsInner();

    /**
     * Model tests for GetFinancialConnectionsOwnersResponseAccountsInner
     */
    @Test
    public void testGetFinancialConnectionsOwnersResponseAccountsInner() {
        // TODO: test GetFinancialConnectionsOwnersResponseAccountsInner
    }

    /**
     * Test the property 'remoteAccountId'
     */
    @Test
    public void remoteAccountIdTest() {
        // TODO: test remoteAccountId
    }

    /**
     * Test the property 'owners'
     */
    @Test
    public void ownersTest() {
        // TODO: test owners
    }

}
