/*
 * Fuse
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fuse.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.fuse.client.model.ConsumerRiskReportTimeFrame;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ConsumerRiskReportCustomization
 */
public class ConsumerRiskReportCustomizationTest {
    private final ConsumerRiskReportCustomization model = new ConsumerRiskReportCustomization();

    /**
     * Model tests for ConsumerRiskReportCustomization
     */
    @Test
    public void testConsumerRiskReportCustomization() {
        // TODO: test ConsumerRiskReportCustomization
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'timeframe'
     */
    @Test
    public void timeframeTest() {
        // TODO: test timeframe
    }

    /**
     * Test the property 'minLimit'
     */
    @Test
    public void minLimitTest() {
        // TODO: test minLimit
    }

    /**
     * Test the property 'maxLimit'
     */
    @Test
    public void maxLimitTest() {
        // TODO: test maxLimit
    }

    /**
     * Test the property 'riskTolerance'
     */
    @Test
    public void riskToleranceTest() {
        // TODO: test riskTolerance
    }

}
