/*
 * Fuse
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fuse.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CreateConsumerRiskReportRequest
 */
public class CreateConsumerRiskReportRequestTest {
    private final CreateConsumerRiskReportRequest model = new CreateConsumerRiskReportRequest();

    /**
     * Model tests for CreateConsumerRiskReportRequest
     */
    @Test
    public void testCreateConsumerRiskReportRequest() {
        // TODO: test CreateConsumerRiskReportRequest
    }

    /**
     * Test the property 'accountId'
     */
    @Test
    public void accountIdTest() {
        // TODO: test accountId
    }

    /**
     * Test the property 'isoCurrencyCode'
     */
    @Test
    public void isoCurrencyCodeTest() {
        // TODO: test isoCurrencyCode
    }

    /**
     * Test the property 'endUserName'
     */
    @Test
    public void endUserNameTest() {
        // TODO: test endUserName
    }

    /**
     * Test the property 'customizationId'
     */
    @Test
    public void customizationIdTest() {
        // TODO: test customizationId
    }

}
