/*
 * Fuse
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fuse.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.fuse.client.model.ConsumerRiskReportTimeFrame;
import org.fuse.client.model.EvalConsumerRiskReportRequestEventsInner;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for EvalConsumerRiskReportRequest
 */
public class EvalConsumerRiskReportRequestTest {
    private final EvalConsumerRiskReportRequest model = new EvalConsumerRiskReportRequest();

    /**
     * Model tests for EvalConsumerRiskReportRequest
     */
    @Test
    public void testEvalConsumerRiskReportRequest() {
        // TODO: test EvalConsumerRiskReportRequest
    }

    /**
     * Test the property 'windowSize'
     */
    @Test
    public void windowSizeTest() {
        // TODO: test windowSize
    }

    /**
     * Test the property 'timeFrame'
     */
    @Test
    public void timeFrameTest() {
        // TODO: test timeFrame
    }

    /**
     * Test the property 'events'
     */
    @Test
    public void eventsTest() {
        // TODO: test events
    }

}
