/*
 * Fuse
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fuse.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.fuse.client.model.AccountSubtype;
import org.fuse.client.model.AccountType;
import org.fuse.client.model.FinancialConnectionsAccountCachedBalance;
import org.fuse.client.model.FinancialConnectionsAccountInstitution;
import org.fuse.client.model.FinancialConnectionsAccountLiabilityAllOfAprs;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for FinancialConnectionsAccountLiability
 */
public class FinancialConnectionsAccountLiabilityTest {
    private final FinancialConnectionsAccountLiability model = new FinancialConnectionsAccountLiability();

    /**
     * Model tests for FinancialConnectionsAccountLiability
     */
    @Test
    public void testFinancialConnectionsAccountLiability() {
        // TODO: test FinancialConnectionsAccountLiability
    }

    /**
     * Test the property 'remoteId'
     */
    @Test
    public void remoteIdTest() {
        // TODO: test remoteId
    }

    /**
     * Test the property 'currency'
     */
    @Test
    public void currencyTest() {
        // TODO: test currency
    }

    /**
     * Test the property 'fingerprint'
     */
    @Test
    public void fingerprintTest() {
        // TODO: test fingerprint
    }

    /**
     * Test the property 'institution'
     */
    @Test
    public void institutionTest() {
        // TODO: test institution
    }

    /**
     * Test the property 'mask'
     */
    @Test
    public void maskTest() {
        // TODO: test mask
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'subtype'
     */
    @Test
    public void subtypeTest() {
        // TODO: test subtype
    }

    /**
     * Test the property 'balance'
     */
    @Test
    public void balanceTest() {
        // TODO: test balance
    }

    /**
     * Test the property 'remoteData'
     */
    @Test
    public void remoteDataTest() {
        // TODO: test remoteData
    }

    /**
     * Test the property 'aprs'
     */
    @Test
    public void aprsTest() {
        // TODO: test aprs
    }

    /**
     * Test the property 'interestRatePercentage'
     */
    @Test
    public void interestRatePercentageTest() {
        // TODO: test interestRatePercentage
    }

    /**
     * Test the property 'originationPrincipalAmount'
     */
    @Test
    public void originationPrincipalAmountTest() {
        // TODO: test originationPrincipalAmount
    }

    /**
     * Test the property 'nextPaymentDueDate'
     */
    @Test
    public void nextPaymentDueDateTest() {
        // TODO: test nextPaymentDueDate
    }

    /**
     * Test the property 'lastPaymentDate'
     */
    @Test
    public void lastPaymentDateTest() {
        // TODO: test lastPaymentDate
    }

    /**
     * Test the property 'lastPaymentAmount'
     */
    @Test
    public void lastPaymentAmountTest() {
        // TODO: test lastPaymentAmount
    }

    /**
     * Test the property 'minimumPaymentAmount'
     */
    @Test
    public void minimumPaymentAmountTest() {
        // TODO: test minimumPaymentAmount
    }

}
