/*
 * Fuse
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fuse.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.fuse.client.model.FinancialConnectionsAccountDetailsAccountNumber;
import org.fuse.client.model.FinancialConnectionsAccountDetailsAch;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for FinancialConnectionsAccountDetails
 */
public class FinancialConnectionsAccountDetailsTest {
    private final FinancialConnectionsAccountDetails model = new FinancialConnectionsAccountDetails();

    /**
     * Model tests for FinancialConnectionsAccountDetails
     */
    @Test
    public void testFinancialConnectionsAccountDetails() {
        // TODO: test FinancialConnectionsAccountDetails
    }

    /**
     * Test the property 'remoteId'
     */
    @Test
    public void remoteIdTest() {
        // TODO: test remoteId
    }

    /**
     * Test the property 'ach'
     */
    @Test
    public void achTest() {
        // TODO: test ach
    }

    /**
     * Test the property 'accountNumber'
     */
    @Test
    public void accountNumberTest() {
        // TODO: test accountNumber
    }

    /**
     * Test the property 'remoteData'
     */
    @Test
    public void remoteDataTest() {
        // TODO: test remoteData
    }

}
