/*
 * Fuse
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fuse.client.model;

import com.google.gson.annotations.SerializedName;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for FinancialConnectionsInvestmentSecurityType
 */
public class FinancialConnectionsInvestmentSecurityTypeTest {
    /**
     * Model tests for FinancialConnectionsInvestmentSecurityType
     */
    @Test
    public void testFinancialConnectionsInvestmentSecurityType() {
        // TODO: test FinancialConnectionsInvestmentSecurityType
    }

}
