/*
 * Fuse
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fuse.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import org.fuse.client.model.Currency;
import org.fuse.client.model.FinancialConnectionsInvestmentSecurityExchange;
import org.fuse.client.model.FinancialConnectionsInvestmentSecurityType;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for FinancialConnectionsInvestmentSecurity
 */
public class FinancialConnectionsInvestmentSecurityTest {
    private final FinancialConnectionsInvestmentSecurity model = new FinancialConnectionsInvestmentSecurity();

    /**
     * Model tests for FinancialConnectionsInvestmentSecurity
     */
    @Test
    public void testFinancialConnectionsInvestmentSecurity() {
        // TODO: test FinancialConnectionsInvestmentSecurity
    }

    /**
     * Test the property 'remoteId'
     */
    @Test
    public void remoteIdTest() {
        // TODO: test remoteId
    }

    /**
     * Test the property 'symbol'
     */
    @Test
    public void symbolTest() {
        // TODO: test symbol
    }

    /**
     * Test the property 'isin'
     */
    @Test
    public void isinTest() {
        // TODO: test isin
    }

    /**
     * Test the property 'sedol'
     */
    @Test
    public void sedolTest() {
        // TODO: test sedol
    }

    /**
     * Test the property 'cusip'
     */
    @Test
    public void cusipTest() {
        // TODO: test cusip
    }

    /**
     * Test the property 'closePrice'
     */
    @Test
    public void closePriceTest() {
        // TODO: test closePrice
    }

    /**
     * Test the property 'currency'
     */
    @Test
    public void currencyTest() {
        // TODO: test currency
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'exchange'
     */
    @Test
    public void exchangeTest() {
        // TODO: test exchange
    }

}
