/*
 * Fuse
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fuse.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for FinancialConnectionsInvestmentSecurityExchange
 */
public class FinancialConnectionsInvestmentSecurityExchangeTest {
    private final FinancialConnectionsInvestmentSecurityExchange model = new FinancialConnectionsInvestmentSecurityExchange();

    /**
     * Model tests for FinancialConnectionsInvestmentSecurityExchange
     */
    @Test
    public void testFinancialConnectionsInvestmentSecurityExchange() {
        // TODO: test FinancialConnectionsInvestmentSecurityExchange
    }

    /**
     * Test the property 'micCode'
     */
    @Test
    public void micCodeTest() {
        // TODO: test micCode
    }

    /**
     * Test the property 'suffix'
     */
    @Test
    public void suffixTest() {
        // TODO: test suffix
    }

}
