/*
 * Fuse
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fuse.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.fuse.client.model.FinancialConnectionDetails;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetFinancialConnectionResponse
 */
public class GetFinancialConnectionResponseTest {
    private final GetFinancialConnectionResponse model = new GetFinancialConnectionResponse();

    /**
     * Model tests for GetFinancialConnectionResponse
     */
    @Test
    public void testGetFinancialConnectionResponse() {
        // TODO: test GetFinancialConnectionResponse
    }

    /**
     * Test the property 'financialConnection'
     */
    @Test
    public void financialConnectionTest() {
        // TODO: test financialConnection
    }

    /**
     * Test the property 'requestId'
     */
    @Test
    public void requestIdTest() {
        // TODO: test requestId
    }

}
