/*
 * Fuse
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fuse.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetRecommendedFinancialInstitutionsRequest
 */
public class GetRecommendedFinancialInstitutionsRequestTest {
    private final GetRecommendedFinancialInstitutionsRequest model = new GetRecommendedFinancialInstitutionsRequest();

    /**
     * Model tests for GetRecommendedFinancialInstitutionsRequest
     */
    @Test
    public void testGetRecommendedFinancialInstitutionsRequest() {
        // TODO: test GetRecommendedFinancialInstitutionsRequest
    }

    /**
     * Test the property 'sessionClientSecret'
     */
    @Test
    public void sessionClientSecretTest() {
        // TODO: test sessionClientSecret
    }

}
